# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
system_RV32M1_cm0plus.c
drivers/fsl_clock.c
drivers/fsl_common.c
drivers/fsl_lpuart.c
drivers/fsl_gpio.c
drivers/fsl_msmc.c
drivers/fsl_intmux.c
drivers/fsl_mu.c
drivers/fsl_sema42.c
gcc/startup_RV32M1_cm0.S
gcc/syscalls_sdk.c
''')
CPPPATH = [cwd, cwd + '/../../CMSIS/Include', cwd + '/drivers', cwd + '/utilities']
CPPDEFINES = ['CPU_RV32M1_cm0plus', 'SDK_DEBUGCONSOLE=0']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
