# RT-Thread building script for component

Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split('''
NXP/RV32M1/Source/Templates/system_RV32M1.c
''')
CPPPATH = [cwd + '/NXP/RV32M1/Include', cwd + '/../CMSIS/Include']
CPPDEFINES = [rtconfig.USE_CORE]
CPPDEFINES += ['USE_SPIFI']
# add for startup script
if rtconfig.USE_CORE =='CORE_M4':
	if rtconfig.CROSS_TOOL == 'gcc':
		src += ['NXP/RV32M1/Source/Templates/GCC/startup_RV32M1_CM4.s']
	elif rtconfig.CROSS_TOOL == 'keil':
		src += ['NXP/RV32M1/Source/Templates/ARM/startup_RV32M1_CM4.s']
	elif rtconfig.CROSS_TOOL == 'iar':
		src += ['NXP/RV32M1/Source/Templates/IAR/startup_RV32M1_CM4.s']
else:
	if rtconfig.CROSS_TOOL == 'gcc':
		src += ['NXP/RV32M1/Source/Templates/GCC/startup_RV32M1_CM0.s']
	elif rtconfig.CROSS_TOOL == 'keil':
		src += ['NXP/RV32M1/Source/Templates/ARM/startup_RV32M1_CM0.s']
	elif rtconfig.CROSS_TOOL == 'iar':
		src += ['NXP/RV32M1/Source/Templates/IAR/startup_RV32M1_CM0.s']
group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
