# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
mcmgr/src/mcmgr.c
mcmgr/src/mcmgr_mu_internal.c
mcmgr/src/mcmgr_internal_core_api_rv32m1.c
rpmsg_lite/lib/common/llist.c
rpmsg_lite/lib/rpmsg_lite/rpmsg_lite.c
rpmsg_lite/lib/rpmsg_lite/rpmsg_ns.c
rpmsg_lite/lib/rpmsg_lite/rpmsg_queue.c
rpmsg_lite/lib/rpmsg_lite/porting/platform/rv32m1/rpmsg_platform.c
rpmsg_lite/lib/virtio/virtqueue.c
''')
CPPPATH = [cwd + '/mcmgr/inc', cwd + '/rpmsg_lite/lib/include', cwd + '/rpmsg_lite/lib/include/platform/rv32m1']

group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
