# for module compiling
import os
from building import *

cwd = str(Dir('#'))
objs = []

CPPPATH = ['applications', 'drivers']

for d in CPPPATH:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

group = DefineGroup('Libraries', objs, depend = [''], CPPPATH = CPPPATH)

Return('group')
