# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Split('''
board.c
startup.c
pin_mux.c
clock_config.c
''')
CPPPATH = [cwd]
CPPDEFINES = ['SDK_SECONDARY_CORE']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
